const BASE = "/hrms";

export const ENDPOINTS = {
  ATTENDANCE_LOG: {
    LIST: `${BASE}/attendance-log/list`,
    SYNC: `${BASE}/attendance-log/sync`,
    DELETE: `${BASE}/attendance-log/delete`,
    IMAGE: `${BASE}/attendance-log/image`,
  },
  ATTENDANCE: {
    LIST: `${BASE}/attendance/list`,
    PREVIEW: `${BASE}/attendance/preview`,
    CALC: `${BASE}/attendance/calc`,
    SUBMIT: `${BASE}/attendance/submit`,
    UPDATE: `${BASE}/attendance/update`,
    DELETE: `${BASE}/attendance/delete`,
  },
  OT_APPROVAL: {
    LIST: `${BASE}/ot-approval/list`,
    APPROVE: `${BASE}/ot-approval/approve`,
    REJECT: `${BASE}/ot-approval/reject`,
  },
  EMPLOYEE: {
    LIST: `${BASE}/employees/list`,
    SYNC: `${BASE}/employees/sync`,
    HELPER: `${BASE}/employees/helper`,
    MACHINE_UPDATE: `${BASE}/employees/machine/update`,
    MACHINE_DEACTIVATE: `${BASE}/employees/machine/deactivate`,
  },
  GATE_PASS: {
    LIST: `${BASE}/gate-pass/list`,
    SUBMIT: `${BASE}/gate-pass/submit`,
    UPDATE: `${BASE}/gate-pass/update`,
    VERIFY_APPROVE: `${BASE}/gate-pass/verify/approve`,
    VERIFY_MANAGER: `${BASE}/gate-pass/verify/manager`,
    VIEW: `${BASE}/gate-pass/view`,
    SCAN: `${BASE}/gate-pass/scan`,
    DELETE: `${BASE}/gate-pass/delete`,
  },
  LEAVE: {
    LIST: `${BASE}/leave/list`,
    SUBMIT: `${BASE}/leave/submit`,
    UPDATE: `${BASE}/leave/update`,
    VERIFY_APPROVE: `${BASE}/leave/verify/approve`,
    VERIFY_MANAGER: `${BASE}/leave/verify/manager`,
    DELETE: `${BASE}/leave/delete`,
  },
  LOAN: {
    LIST: `${BASE}/loan/list`,
    SUBMIT: `${BASE}/loan/submit`,
    UPDATE: `${BASE}/loan/update`,
    VERIFY_APPROVE: `${BASE}/loan/verify/approve`,
    VERIFY_MANAGER: `${BASE}/loan/verify/manager`,
    DELETE: `${BASE}/loan/delete`,
    DEDUCTIONS_LIST: `${BASE}/loan/deductions/list`,
  },
  LOAN_DEDUCTION: {
    LIST: `${BASE}/loan-deduction/list`,
    DETAIL: `${BASE}/loan-deduction/detail`,
    MARK: `${BASE}/loan-deduction/mark`,
    UNDO: `${BASE}/loan-deduction/undo`,
    APPROVE: `${BASE}/loan-deduction/approve`,
    EXTRA: `${BASE}/loan-deduction/extra`,
    EXTRA_UPDATE: `${BASE}/loan-deduction/extra/update`,
    EXTRA_DELETE: `${BASE}/loan-deduction/extra/delete`,
  },
};
