const CORE_API = "/core";

export const CORE_ENDPOINTS = {
  AUTH: {
    LOGIN: `${CORE_API}/auth/login`,
    LOGOUT: `${CORE_API}/auth/logout`,
    ME: `${CORE_API}/auth/me`,
    CHANGE_PASSWORD: `${CORE_API}/auth/password`,
    STATS: `${CORE_API}/auth/stats`,
  },
  USERS: {
    LIST: `${CORE_API}/auth/users/list`,
    IMS: `${CORE_API}/auth/users/ims`,
    GET: `${CORE_API}/auth/users/get`,
    CREATE: `${CORE_API}/auth/users/create`,
    UPDATE: `${CORE_API}/auth/users/update`,
    DELETE: `${CORE_API}/auth/users/delete`,
    HELPER: `${CORE_API}/auth/users/helper`,
  },
  PERMISSIONS: {
    LIST: `${CORE_API}/auth/permissions/list`,
    GET: `${CORE_API}/auth/permissions/get`,
    SET: `${CORE_API}/auth/permissions/set`,
    SET_BULK: `${CORE_API}/auth/permissions/set-bulk`,
    UPDATE: `${CORE_API}/auth/permissions/update`,
    REMOVE: `${CORE_API}/auth/permissions/remove`,
  },
  MODULES: {
    LIST: `${CORE_API}/auth/modules/list`,
    GET: `${CORE_API}/auth/modules/get`,
    CREATE: `${CORE_API}/auth/modules/create`,
    UPDATE: `${CORE_API}/auth/modules/update`,
    TOGGLE_STATUS: `${CORE_API}/auth/modules/toggle-status`,
    VIEWS: `${CORE_API}/auth/modules/helper`,
  },
  DEPARTMENTS: {
    LIST: `${CORE_API}/auth/departments/list`,
    GET: `${CORE_API}/auth/departments/get`,
    CREATE: `${CORE_API}/auth/departments/create`,
    UPDATE: `${CORE_API}/auth/departments/update`,
    DELETE: `${CORE_API}/auth/departments/delete`,
    HELPER: `${CORE_API}/auth/departments/helper`,
  },
  DESIGNATIONS: {
    LIST: `${CORE_API}/auth/designations/list`,
    GET: `${CORE_API}/auth/designations/get`,
    CREATE: `${CORE_API}/auth/designations/create`,
    UPDATE: `${CORE_API}/auth/designations/update`,
    DELETE: `${CORE_API}/auth/designations/delete`,
    HELPER: `${CORE_API}/auth/designations/helper`,
  },
  TRAINING: {
    VIDEOS: {
      LIST: `${CORE_API}/training/list`,
      GET: `${CORE_API}/training/get`,
      CREATE: `${CORE_API}/training/create`,
      UPDATE: `${CORE_API}/training/update`,
      DELETE: `${CORE_API}/training/delete`,
      VIEWS: `${CORE_API}/training/helper`,
    },
    SOPS: {
      LIST: `${CORE_API}/sop/list`,
      GET: `${CORE_API}/sop/get`,
      CREATE: `${CORE_API}/sop/create`,
      UPDATE: `${CORE_API}/sop/update`,
      DELETE: `${CORE_API}/sop/delete`,
      HELPER: `${CORE_API}/sop/helper`,
    }
  },
  ACTIVITY_LOGS: {
    LIST: `${CORE_API}/activity-logs`,
  },
  INBOX: {
    LIST: `${CORE_API}/inbox`,
    UNREAD_COUNT: `${CORE_API}/inbox/unread-count`,
    read: (id) => `${CORE_API}/inbox/${id}/read`,
    READ_ALL: `${CORE_API}/inbox/read-all`,
  },
  PUSH: {
    VAPID_PUBLIC_KEY: `${CORE_API}/push/vapid-public-key`,
    SUBSCRIBE: `${CORE_API}/push/subscribe`,
    LINK: `${CORE_API}/push/link`,
    UNLINK: `${CORE_API}/push/unlink`,
    UNSUBSCRIBE: `${CORE_API}/push/unsubscribe`,
    DELIVERY_RECEIVED: `${CORE_API}/push/delivery/received`,
    DELIVERY_READ: `${CORE_API}/push/delivery/read`,
    LOGS: `${CORE_API}/push/logs`,
    SEND: `${CORE_API}/push/send`,
  },
  // USER_PREFERENCES: `${CORE_API}/user-preferences`,
  APP_CONFIG: {
    LIST: "/app-config/list",
    UPDATE: "/app-config",
  },
};
