/** RM Store API endpoints — mounted at `/api/rmstore/...` (client prepends `/api`). */
const BASE = "/rmstore";

export const ENDPOINTS = {
  PRODUCTION: {
    LIST: `${BASE}/production/list`,
    GET: `${BASE}/production/get`,
    CREATE: `${BASE}/production/create`,
    UPDATE: `${BASE}/production/update`,
    DELETE: `${BASE}/production/delete`,
    PRODUCTION_ITEMS_VIEWS: `${BASE}/production/production-items/helper`,
    RM_ITEMS_VIEWS: `${BASE}/production/rm-items/helper`,
    PRD_RUN_JC_VIEWS: `${BASE}/production/prd-run-jc/helper`,
  },
  SPEC: {
    LIST: `${BASE}/spec/list`,
    GET: `${BASE}/spec/get`,
    CREATE: `${BASE}/spec/create`,
    UPDATE: `${BASE}/spec/update`,
    DELETE: `${BASE}/spec/delete`,
  },
  STORE_LOCATION: {
    LIST: `${BASE}/store-locations/list`,
    GET: `${BASE}/store-locations/get`,
    CREATE: `${BASE}/store-locations/create`,
    UPDATE: `${BASE}/store-locations/update`,
    DELETE: `${BASE}/store-locations/delete`,
    VIEWS: `${BASE}/store-locations/helper`,
  },
  MRN: {
    LIST: `${BASE}/mrn/list`,
    GENERATE: `${BASE}/mrn/generate`,
    DELETE: `${BASE}/mrn/delete`,
    DETAIL: `${BASE}/mrn/detail`,
    COILS: `${BASE}/mrn/coils`,
    GENERATE_STICKERS: `${BASE}/mrn/generate-stickers`,
    SAVE_STICKER_DRAFT: `${BASE}/mrn/save-sticker-draft`,
    UPLOAD_DOCS: `${BASE}/mrn/upload-docs`,
    STICKER_PREVIEW: `${BASE}/mrn/sticker/preview`,
    STICKER_RENDER_SINGLE: `${BASE}/mrn/sticker/render-single`,
    STICKER_RENDER_BULK: `${BASE}/mrn/sticker/render-bulk`,
    STICKER_RENDER_BATCH_QC: `${BASE}/mrn/sticker/render-batch-qc`,
  },
  COIL: {
    LIST: `${BASE}/coils/list`,
    GET: `${BASE}/coils/get`,
  },
  INVENTORY_INWARDS: {
    LIST: `${BASE}/inventory-inwards/list`,
    PENDING_LIST: `${BASE}/inventory-inwards/pending-list`,
    PACKING_AREA_LIST: `${BASE}/inventory-inwards/packing-area-list`,
    COIL_AREA: `${BASE}/inventory-inwards/coil-area-list`,
    GET: `${BASE}/inventory-inwards/get`,
    CREATE: `${BASE}/inventory-inwards/create`,
    UPDATE: `${BASE}/inventory-inwards/update`,
    APPROVE: `${BASE}/inventory-inwards/approve`,
    DELETE: `${BASE}/inventory-inwards/delete`,
  },
  QC_CHECK: {
    LIST: `${BASE}/qc-checks/list`,
    GET: `${BASE}/qc-checks/get`,
    PREPARE: `${BASE}/qc-checks/prepare`,
    SUBMIT: `${BASE}/qc-checks/submit`,
    APPROVE: `${BASE}/qc-checks/approve`,
    REOPEN: `${BASE}/qc-checks/reopen`,
    DELETE: `${BASE}/qc-checks/delete`,
  },
  RM_REJECTION: {
    LIST: `${BASE}/rm-rejections/list`,
    PENDING_LIST: `${BASE}/rm-rejections/pending-list`,
    GET: `${BASE}/rm-rejections/get`,
    CREATE: `${BASE}/rm-rejections/create`,
    REGISTER_FROM_CHECK: `${BASE}/rm-rejections/register-from-check`,
    GENERATE_STORE_OUT: `${BASE}/rm-rejections/generate-store-out`,
    GENERATE_STORE_OUT_FROM_IPR: `${BASE}/rm-rejections/generate-store-out-from-ipr`,
    APPROVE_REGISTER: `${BASE}/rm-rejections/approve-register`,
    UPDATE_BILL: `${BASE}/rm-rejections/update-bill`,
    BILL_NUMBERS: `${BASE}/rm-rejections/bill-helper`,
    DELETE: `${BASE}/rm-rejections/delete`,
  },
  ISSUE_REQUEST: {
    LIST: `${BASE}/issue-requests/list`,
    LIST_JOB_CARDS: `${BASE}/issue-requests/list-job-cards`,
    GET: `${BASE}/issue-requests/get`,
    JOB_CARD_SUMMARY: `${BASE}/issue-requests/job-card-summary`,
    AVAILABLE_COILS: `${BASE}/issue-requests/available-coils`,
    CREATE: `${BASE}/issue-requests/create`,
    UPDATE: `${BASE}/issue-requests/update`,
    APPROVE: `${BASE}/issue-requests/approve`,
    DELETE: `${BASE}/issue-requests/delete`,
    LOCK_STORE_OUT: `${BASE}/issue-requests/lock-store-out`,
    UNLOCK_STORE_OUT: `${BASE}/issue-requests/unlock-store-out`,
  },
  IN_PROCESS_REQUEST: {
    LIST: `${BASE}/in-process-requests/list`,
    GET: `${BASE}/in-process-requests/get`,
    REASONS: `${BASE}/in-process-requests/reasons`,
    PENDING_STORE_IN: `${BASE}/in-process-requests/pending-store-in`,
    PENDING_STORE_OUT: `${BASE}/in-process-requests/pending-store-out`,
    CREATE: `${BASE}/in-process-requests/create`,
    UPDATE: `${BASE}/in-process-requests/update`,
    APPROVE: `${BASE}/in-process-requests/approve`,
    COMPLETE_STORE_IN: `${BASE}/in-process-requests/complete-store-in`,
    DELETE: `${BASE}/in-process-requests/delete`,
  },
  OUT_ENTRY: {
    LIST: `${BASE}/out-entries/list`,
    PENDING_LIST: `${BASE}/out-entries/pending-list`,
    STORED_MRNS: `${BASE}/out-entries/stored-mrn-list`,
    STORED_MRN_DETAIL: `${BASE}/out-entries/stored-mrn-detail`,
    GET: `${BASE}/out-entries/get`,
    CREATE: `${BASE}/out-entries/create`,
    UPDATE: `${BASE}/out-entries/update`,
    APPROVE: `${BASE}/out-entries/approve`,
    DELETE: `${BASE}/out-entries/delete`,
  },
  STOCK_ADJUSTMENT: {
    LIST: `${BASE}/stock-adjustment/list`,
    GET: `${BASE}/stock-adjustment/get`,
    ACTIVE_COILS: `${BASE}/stock-adjustment/active-coils`,
    CREATE: `${BASE}/stock-adjustment/create`,
    UPDATE: `${BASE}/stock-adjustment/update`,
    DELETE: `${BASE}/stock-adjustment/delete`,
    STICKER_RENDER_SINGLE: `${BASE}/stock-adjustment/sticker/render-single`,
    STICKER_RENDER_BULK: `${BASE}/stock-adjustment/sticker/render-bulk`,
  },
  INVENTORY_REPORT: {
    LIST: `${BASE}/inventory-report/list`,
  },
  COIL_TRANSACTION_LOGS: {
    LIST: `${BASE}/logs/coil-transactions/list`,
  },
  STICKER_DOWNLOAD_LOGS: {
    LIST: `${BASE}/logs/sticker-downloads/list`,
  },
  COIL_DOWNLOAD_LOGS: {
    LIST: `${BASE}/logs/sticker-downloads/list`,
  },
};
